### PR TITLE
Add basic systemd support

### PR DESCRIPTION
**Pull request by jbreitbart**
This should enable support for systemd cgroup directory structure. It can be disabled via a CMake option.

Tested on
- my local machine with systemd
- mac-snb27 without systemd

### CODE REVIEW

**Comment by weidendo** [comment]
Can't it be detected automatically if a system is using the systemd structure, and just do the right thing?
(... und batsch!)

**Comment by jbreitbart** [comment]
Hmm, well, I agree that the CMake option is not a good solution, especially if ponci is built as part of another project, but an automatic detection in CMake probably makes the build system complex without any real benefit.

I'll switch the current solution to on that is based on an env variable. We can change that to a real check at runtime ... but I am not sure how to check if the system uses systemd. Any idea?

**Comment by weidendo** [comment]
if the output of "mount" contains "cgroup on /sys/fs/cgroup/systemd type cgroup" ? Or is this just Ubuntu?
Never wrote a check for cmake...

**Comment by jbreitbart** [comment]
Good question. Let's try to summon some non-ubuntu user. Oh @spickartz @stlankes :smile:

**Comment by jbreitbart** [comment]
I have updated the code. It checks `/etc/mtab` in a constructor.

**Comment by jbreitbart** [comment]
I have checked swarm1 (CAT Haswell) / hector (KNL) and the mount is identical to Ubuntu, so I guess the detection is fine for now.

**Pull request merged**
